spring.application.name=UserManagment
server.port=8080
spring.h2.console.enabled=true
spring.jpa.properties.javax.persistence.validation.mode=none
management.metrics.export.prometheus.enabled=true
management.endpoints.web.exposure.include=prometheus
management.endpoint.prometheus.enabled=true

